### ISSUE TITLE
src/main/scala/com/aliyun/emr/example/streaming/RedisWordCount.scala.1 这个是啥意思？

### ISSUE THREAD

**Issue by jmu** [aliyun/aliyun-emapreduce-demo#18]
src/main/scala/com/aliyun/emr/example/streaming/RedisWordCount.scala.1

后面带了.1 是不能用还是什么意思

**Comment by uncleGen** [comment]
Maven库中没有现成可用用的spark-redis包，所以用“.1”避免这个文件的编译失败。
