### ISSUE TITLE
from odps import OdpsOps 无法导入

### ISSUE THREAD

**Issue by ghost** [aliyun/aliyun-emapreduce-demo#20]
python版本的 odps里面没有这个OdpsOps类。怎么解决？

**Comment by uncleGen** [comment]
通过--jars将相应地包加进去

**Comment by uncleGen** [comment]
看下这个文档：https://github.com/aliyun/aliyun-emapreduce-sdk/blob/master-2.x/docs/how_to_run_spark_with_python_sdk.md

**Comment by superdog0085** [comment]
> 看下这个文档：https://github.com/aliyun/aliyun-emapreduce-sdk/blob/master-2.x/docs/how_to_run_spark_with_python_sdk.md

试过了，不行的。我用的是pyspark。提示说没有main class。

**Comment by uncleGen** [comment]
close stale issue
