### ISSUE TITLE
tf_fm_on_spark.py : Zip operation fail in dealing with spark dataframe

### ISSUE THREAD

**Issue by Zarca** [aliyun/aliyun-emapreduce-demo#48]
Hello,I follow the demo in the project path :
/aliyun-emapreduce-demo/src/main/python/deeplearning/tf_fm_on_spark.py

Therefore I got some problems about the zip operation in line 137~138 as the picture below shows:

![image](https://user-images.githubusercontent.com/24642659/74215630-a56b2500-4cdc-11ea-86d3-c97bf4689b08.png)

Q1:Are the user_sub, genres_sub and rating_sub are still  Dataframe column object or numpy arrays?

Q2:If they are DataFrame column , will the codes between line 137-138 cause the "collect()" operation in Spark DataFrame?  

Q3:I find out that the zip operation can't be applied on the dataframe column object in Spark, the error message is present below:
![image](https://user-images.githubusercontent.com/24642659/74217842-8de36a80-4ce3-11ea-9e25-5795a80ba644.png)

**Comment by uncleGen** [comment]
cc @jiangyu
