### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by cz7169** [aliyun/aliyun-emapreduce-demo#8]
1.Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.0:compile (execution: scala-compile-first, phase: process-resources)	pom.xml	/examples	line 280	Maven Project Build Lifecycle Mapping Problem
2.Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.0:testCompile (execution: scala-test-compile-first, phase: process-test-resources)	pom.xml	/examples	line 287	Maven Project Build Lifecycle Mapping Problem

**Comment by uncleGen** [comment]
hello, could you please give some infomations about the build enviroment and platform?

**Comment by cz7169** [comment]
Thanks ,I have fixed these problems,But I found a new problem:)
